# Generated by Django 5.2.3 on 2025-07-07 22:39

import django.db.models.deletion
import mentor_ship.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_ship", "0001_create_class_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=(models.Model, mentor_ship.models.DataTimeMixin),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience",
                    models.IntegerField(verbose_name="experience in specialisation"),
                ),
                (
                    "specialisation",
                    models.ForeignKey(
                        default="specialisation",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="mentor_ship.specialisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
            },
            bases=(models.Model, mentor_ship.models.DataTimeMixin),
        ),
    ]
