# Generated by Django 5.2.3 on 2025-07-08 22:28

import django.db.models.deletion
import mentor_ship.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_ship", "0003_create_class_student"),
        ("testing_sistem", "0001_create_course_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_the_group", models.CharField(blank=True, max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_sistem.course",
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(blank=True, to="mentor_ship.student"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentor_ship.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
            bases=(models.Model, mentor_ship.models.DataTimeMixin),
        ),
    ]
