# Generated by Django 5.2.3 on 2025-07-19 18:39

import django.db.models.deletion
import mentor_ship.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing_sistem", "0001_create_model_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TimeField()),
                ("index_number", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_sistem.course",
                    ),
                ),
                (
                    "image",
                    models.ManyToManyField(
                        blank=True, null=True, to="testing_sistem.image"
                    ),
                ),
            ],
            options={
                "verbose_name": "topic",
                "verbose_name_plural": "topics",
            },
            bases=(models.Model, mentor_ship.mixins.DataTimeMixin),
        ),
    ]
