# Generated by Django 5.2.3 on 2025-07-12 12:34

import django.db.models.deletion
import mentor_ship.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_ship", "0004_create_model_group"),
        ("testing_sistem", "0002_create_model_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentor_ship.teacher",
                    ),
                ),
                (
                    "topic_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_sistem.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
            bases=(models.Model, mentor_ship.mixins.DataTimeMixin),
        ),
    ]
