# Generated by Django 5.2.3 on 2025-07-14 18:36

import django.db.models.deletion
import mentor_ship.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_ship", "0004_create_model_group"),
        ("testing_sistem", "0003_create_model_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TimeField()),
                ("is_open", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentor_ship.teacher",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_sistem.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "test",
                "verbose_name_plural": "tests",
            },
            bases=(models.Model, mentor_ship.mixins.DataTimeMixin),
        ),
    ]
