# Generated by Django 5.2.3 on 2025-07-14 18:38

import django.db.models.deletion
import mentor_ship.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing_sistem", "0005_create_model_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing_sistem.questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
            },
            bases=(models.Model, mentor_ship.mixins.DataTimeMixin),
        ),
    ]
